#!/usr/bin/env python3
"""
convert_adblock_to_domains.py

Adblock Plus 形式のフィルタリストからドメインリストを抽出し、
ESP32C6 DNS フィルタリング用の domain.txt に変換します。

使用方法:
    python3 convert_adblock_to_domains.py <input_adblock.txt> <output_domains.txt>

例:
    python3 convert_adblock_to_domains.py Adblock_Plus_list.txt domain.txt
"""

import re
import sys
from urllib.parse import urlparse


def extract_domain_from_adblock_rule(line):
    """Adblock Plus ルールからドメイン名を抽出"""
    line = line.strip()

    # 空行とコメント行をスキップ
    if not line or line.startswith('!') or line.startswith('#'):
        return None

    # ホワイトリスト（@@で始まる）をスキップ
    if line.startswith('@@'):
        return None

    # CSS セレクタ（## や #@# を含む）をスキップ
    if '##' in line or '#@#' in line or '#?#' in line:
        return None

    # ||domain^ 形式
    if line.startswith('||') and '^' in line:
        domain = line[2:].split('^')[0]
        # パスを含む場合はドメイン部分のみ抽出
        if '/' in domain:
            domain = domain.split('/')[0]
        return domain

    # |http://domain または |https://domain 形式
    if line.startswith('|http'):
        try:
            parsed = urlparse(line[1:])
            return parsed.netloc
        except:
            return None

    # domain^ 形式（||なし）
    if '^' in line and not line.startswith('/'):
        domain = line.split('^')[0]
        if '/' in domain:
            domain = domain.split('/')[0]
        # ドメイン形式かチェック
        if '.' in domain and not domain.startswith('.'):
            return domain

    return None


def is_valid_domain(domain):
    """ドメイン名の妥当性チェック"""
    if not domain or len(domain) < 3 or len(domain) > 253:
        return False

    # 不正な文字チェック
    if ' ' in domain or '..' in domain:
        return False

    # 最低1つのドットが必要
    if '.' not in domain:
        return False

    # 基本的な文字チェック（英数字、ハイフン、ドット、アンダースコア）
    if not re.match(r'^[a-zA-Z0-9\.\-_]+$', domain):
        return False

    return True


def convert_adblock_to_domains(input_file, output_file):
    """Adblock Plus リストをドメインリストに変換"""
    domains = set()  # 重複排除のため set を使用

    print(f"Reading from {input_file}...")

    with open(input_file, 'r', encoding='utf-8') as f:
        for line_num, line in enumerate(f, 1):
            domain = extract_domain_from_adblock_rule(line)
            if domain and is_valid_domain(domain):
                domains.add(domain.lower())

            # 進捗表示
            if line_num % 1000 == 0:
                print(f"Processed {line_num} lines, found {len(domains)} unique domains...")

    print(f"\nTotal unique domains found: {len(domains)}")

    # ドメインをソートして出力
    sorted_domains = sorted(domains)

    print(f"Writing to {output_file}...")
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("# Domain blocklist converted from Adblock Plus format\n")
        f.write(f"# Total domains: {len(sorted_domains)}\n")
        f.write("# Generated by convert_adblock_to_domains.py\n")
        f.write("\n")

        for domain in sorted_domains:
            f.write(domain + '\n')

    print(f"Done! {len(sorted_domains)} domains written to {output_file}")


def main():
    if len(sys.argv) != 3:
        print("Usage: python3 convert_adblock_to_domains.py <input_adblock.txt> <output_domains.txt>")
        print("\nExample:")
        print("  python3 convert_adblock_to_domains.py Adblock_Plus_list.txt domain.txt")
        sys.exit(1)

    input_file = sys.argv[1]
    output_file = sys.argv[2]

    try:
        convert_adblock_to_domains(input_file, output_file)
    except FileNotFoundError:
        print(f"Error: File '{input_file}' not found")
        sys.exit(1)
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)


if __name__ == '__main__':
    main()
